### ISSUE TITLE
1° Feedback Portafolio

### ISSUE THREAD

**Issue by nerdale** [VioletaLibertad/violetalibertad.github.io#1]
Violeta,

1. Muy bueno el efecto del inicio de la página, te recomiendo revisar alguna manera de darle un poco más de energía al cubo, el color blanco con líneas negras lo apagan un poco.

2. En general la paleta de colores es bastante opaca, no se genera un contraste real de los colores por lo que pareciera no resaltar, puedes jugar con los colores y sus tonalidades [acá](https://color.adobe.com/es/create/color-wheel/?base=2&rule=Analogous&selected=0&name=Mi%20tema%20de%20Color&mode=rgb&rgbvalues=1,0.3137254901960784,0.050000000000000044,0.91,0.16549509803906517,0.04550000000000004,1,0,0,0.91,0.04550000000000004,0.4569117647062087,1,0.050000000000000044,0.9542016806736342&swatchOrder=0,1,2,3,4)

3. La diagramación de los elementos es un poco predecible, puedes jugar de la misma manera sin que se pierda el orden realmente, como por ejemplo [acá](http://themeelite.com/demos/xpro/personal-version/animated-text/) (bajar hasta la sección portfolio) o [acá](http://template.metrika.itembridge.com/version1.html)

4. Te recomiendo darle un poco de dinamismo al sitio jugando tanto con transiciones entre sección y sección, como también con movimientos de los elementos en sus entradas, te dejo como ejemplo el sitio de [atomic object](https://atomicobject.com/) quien juega mucho con eso (debes hacer scroll hacia abajo)

5. Ojo en general con los colores, el menú hamburguesa es negro sobre fondo negro.

6. Recuerda que debe ser full responsive

7. Ojo con un scroll horizontal que tienes, debes tener un margen, padding o elemento saliendose de su contenedor.

8. Cualquier cosa estamos por acá.

Saludos

**Comment by VioletaLibertad** [comment]
Gracias Ale! Sé que me faltan muchas cosas por mejorar aún, asiq aplicaré lo que me indicas :)

Estamos en contacto :smile:
